name: Deploy documentation

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    strategy:
      matrix:
        apps:
          - name: butterfly
            directory: launch.butterfly.linwood
            env: |
              APP_NAME=Butterfly
              APP_DOWNLOAD_URL=https://butterfly.linwood.dev/downloads
              APP_WEB_URL=https://butterfly.linwood.dev
              APP_WEB_PREVIEW_URL=https://preview.butterfly.linwood.dev
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Add env
        run: |
          echo ${{ matrix.apps.env }} >> .env
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Deploy to SFTP
        if: github.ref == 'refs/heads/develop'
        env:
          SFTP_HOST: ${{ secrets.SFTP_HOST }}
          SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
          SFTP_KEY: ${{ secrets.SFTP_KEY }}
          SFTP_KNOWN_HOSTS: ${{secrets.SFTP_KNOWN_HOSTS}}
        run: |
          echo "$SFTP_KEY" > sftp_key
          chmod 600 sftp_key
          echo "$SFTP_KNOWN_HOSTS" > known_hosts
          chmod 600 known_hosts
          rsync -avz --delete -e "ssh -i sftp_key -o UserKnownHostsFile=known_hosts" dist/ $SFTP_USERNAME@$SFTP_HOST:/var/www/${{ matrix.apps.directory }}
